site_name: OpSisttems - Documentação
site_description: Documentação técnica do sistema OpSisttems
site_author: Móveis Gottems

theme:
  name: material
  language: pt-BR

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Início: index.md

  - Versões:
      - 1.x:
          - 1.9: versoes/1.9.md
          - 1.8: versoes/1.8.md
          - 1.7: versoes/1.7.md
          - 1.6: versoes/1.6.md
          - 1.5: versoes/1.5.md
          - 1.4: versoes/1.4.md
          - 1.3: versoes/1.3.md
          - 1.2: versoes/1.2.md
          - 1.1: versoes/1.1.md

  - Diário Técnico: diario-tecnico.md

  - Programação:
      - Programação: programacao.md
      - Produção Produtos: producao.md
      - PCP Simplificado: pcp-simplificado.md

  - Engenharia:
      - Ficha Técnica: ficha-tecnica.md
      - Tempos de Processo: tempos.md

  - Estoque:
      - Estoque Montagem: estoque-componente.md
      - Visualizador de Lote: visualizador-lote.md

  - Manutenção: manutencao.md