site_name: OpSisttems - Documentação
site_description: Documentação técnica do sistema OpSisttems
site_author: Móveis Gottems

theme:
  name: material
  language: pt-BR

nav:
  - Início: index.md
  - Diário Técnico: diario-tecnico.md
  - Programação:
      - Programação: programacao.md
      - Produção Produtos: producao.md
      - PCP Simplificado: pcp-simplificado.md
  - Engenharia:
      - Ficha Técnica: ficha-tecnica.md
      - Tempos de Processo: tempos.md
  - Estoque:
      - Estoque Componentes: estoque-componente.md
      - Visualizador de Lote: visualizador-lote.md
  - Manutenção: manutencao.md